import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../../globals.css";
import { SideNav } from "@/component/nav/sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <section className="w-[13vw] h-[100vh] border hidden md:flex">
        <SideNav />
      </section>
      <section className="w-[87vw]">{children}</section>
    </div>
  );
}
